export const TOOL_SIGNATURES = {
  "account_register": "(account_id: str, asset_id: str | None = None, date_from: str | None = None, date_to: str | None = None, time_from: str | None = None, time_to: str | None = None, branch: str | None = None, status: str | None = None, limit: int = 100, offset: int = 0, summary: bool = False) -> dict",
  "add_match_rule": "(account_id: str, pattern: str) -> dict",
  "add_match_rules": "(rules: list[dict]) -> dict",
  "age_of_money": "(days: int = 30) -> dict",
  "apply_match_rules": "(catch_all_account_id: str, date_from: str | None = None, date_to: str | None = None, dry_run: bool = True) -> dict",
  "apply_pattern": "(pattern: str, target_account: str, force: bool = False, persist_rule: bool = False, dry_run: bool = True, source_account: str | None = None, date_from: str | None = None, date_to: str | None = None) -> dict",
  "apply_reconciliation_plan": "(file_path: str, account_id: str, counterpart_account_id: str, expected_balance: float | None = None, currency: str = 'USD', asset_id: str | None = None, date_col: str | None = None, amount_col: str | None = None, desc_col: str | None = None, inflow_col: str | None = None, outflow_col: str | None = None, skip_rows: int = 0, amount_convention: str = 'signed', statement_type: str | None = None, date_tolerance_days: int = 3, min_likely_score: float = 0.72, row_indexes: list[int] | None = None, commit_imported: bool = False, annotate_posted_matches: bool = True, allow_review_skip: bool = False, require_balance_match: bool = True, dry_run: bool = True) -> dict",
  "apply_rollover": "(year: int, month: int) -> dict",
  "assert_balance": "(account_id: str, expected: float, date: str | None = None, asset_id: str | None = None, status: str | None = None) -> dict",
  "assert_balances": "(assertions: list, status: str | None = None) -> dict",
  "audit_categorization": "(date_from: str | None = None, date_to: str | None = None, min_occurrences: int = 2, status: str = 'posted', mode: str = 'budget') -> dict",
  "backup_now": "(output_path: str | None = None, compact: bool = False) -> dict",
  "backup_status": "() -> dict",
  "balance_sheet": "(date: str | None = None, branch: str | None = None, compact: bool = False, include_pending: bool = False, hide_zero: bool = False, quote_asset_id: str | None = None, account_ids: list[str] | None = None, entity_id: str | None = None) -> dict",
  "budget_rollover_preview": "(year: int, month: int) -> dict",
  "budget_status": "(account: str | None = None, year: int | None = None, month: int | None = None, rollup: bool = False, status: str = 'posted', quote_asset_id: str | None = None) -> dict",
  "budget_summary": "(year: int | None = None, month: int | None = None, status: str = 'posted', quote_asset_id: str | None = None) -> dict",
  "buy_security": "(account_id: str, symbol: str, shares: float, total_cost_cents: int, date: str, commission_cents: int = 0, status: str = 'posted') -> dict",
  "cash_flow": "(year: int, month: int, branch: str | None = None, compact: bool = False, include_pending: bool = False, quote_asset_id: str | None = None) -> dict",
  "cash_projection": "(year: int | None = None, month: int | None = None, asset_account_ids: list[str] | None = None, liability_account_ids: list[str] | None = None, entity_id: str | None = None, earmarks: list[dict] | None = None, include_pending: bool = True, include_planned: bool = True, quote_asset_id: str | None = None) -> dict",
  "close_period": "(name: str, as_of: str, description: str | None = None) -> dict",
  "commit_batch": "(tx_ids: list[str] | None = None, batch_id: str | None = None, date_from: str | None = None, date_to: str | None = None, account_id: str | None = None, dry_run: bool = False) -> dict",
  "compare_scenarios": "(branch_a: str | None = None, branch_b: str | None = None, as_of_a: str | None = None, as_of_b: str | None = None, asset_id: str | None = None) -> dict",
  "consolidate_transfers": "(account_a: str, account_b: str, transfer_account_id: str | None = None, date_tolerance_days: int = 1, dry_run: bool = True) -> dict",
  "copy_budgets": "(from_year: int, from_month: int, to_year: int, to_month: int) -> dict",
  "count_transactions": "(account_id: str | None = None, status: str | None = None, date_from: str | None = None, date_to: str | None = None) -> dict",
  "create_account": "(name: str, type: str, code: str = '', parent_id: str = '', color_hex: str = '#888888') -> dict",
  "create_accounts": "(accounts: list[dict]) -> dict",
  "create_asset": "(symbol: str, asset_type: str = 'currency', decimals: int = 2, name: str = '') -> dict",
  "create_branch": "(name: str) -> dict",
  "create_price": "(asset_id: str, quote_id: str, rate: float, time: str) -> dict",
  "create_scheduled_transaction": "(date: str, amount: float, from_account_id: str, to_account_id: str, description: str = '', frequency: str = 'monthly', end_date: str | None = None) -> dict",
  "create_transaction": "(date: str, amount: float, from_account_id: str, to_account_id: str, description: str, status: str = 'pending', asset_id: str | None = None, branch: str | None = None) -> dict",
  "delete_account": "(id: str) -> dict",
  "delete_asset": "(asset_id: str, force: bool = False) -> dict",
  "delete_budget": "(account: str, year: int | None = None, month: int | None = None, include_overrides: bool = False) -> dict",
  "delete_budgets": "(accounts: list[str] | None = None, year: int | None = None, month: int | None = None, include_overrides: bool = False) -> dict",
  "delete_goal": "(account: str) -> dict",
  "delete_match_rule": "(account_id: str, pattern: str) -> dict",
  "delete_match_rules": "(rules: list[dict]) -> dict",
  "delete_tag": "(tag_id: str) -> dict",
  "delete_tags": "(entity_type: str, entity_id: str, key: str | None = None, val: str | None = None, dry_run: bool = True) -> dict",
  "delete_transaction": "(id: str, hard_delete: bool = False) -> dict",
  "detect_recurring": "(months: int = 6, year: int | None = None, month: int | None = None, min_occurrences: int = 2, amount_tolerance_pct: float = 5.0, account_id: str | None = None) -> list[dict]",
  "discard_batch": "(tx_ids: list[str] | None = None, batch_id: str | None = None, date_from: str | None = None, date_to: str | None = None, account_id: str | None = None, dry_run: bool = True) -> dict",
  "discard_branch": "(name: str) -> dict",
  "export_ledger": "(output_path: str | None = None, entity_id: str | None = None, date_from: str | None = None, date_to: str | None = None, account_ids: list[str] | None = None) -> dict",
  "export_transactions": "(account_id: str | None = None, date_from: str | None = None, date_to: str | None = None, output_path: str | None = None) -> dict",
  "financial_overview": "(year: int | None = None, month: int | None = None, status: str = 'active', quote_asset_id: str | None = None) -> dict",
  "financial_picture": "(year: int | None = None, month: int | None = None, quote_asset_id: str | None = None, status: str = 'combined', include_pending: bool = True) -> dict",
  "find_pending_duplicates": "(account_id: str | None = None, date_from: str | None = None, date_to: str | None = None, date_tolerance_days: int = 3) -> dict",
  "flip_entries": "(tx_ids: list[str]) -> dict",
  "forecast": "(account_id: str, as_of: str | None = None) -> dict",
  "forecast_month_end": "(year: int | None = None, month: int | None = None, status: str = 'posted', quote_asset_id: str | None = None) -> dict",
  "fx_transfer": "(from_account_id: str, to_account_id: str, from_amount: float, to_amount: float, from_asset_id: str, to_asset_id: str, fx_account_id: str, date: str, description: str, status: str = 'posted', record_rate: bool = True) -> dict",
  "get_account": "(id: str) -> dict",
  "get_account_by_name": "(name: str) -> dict | None",
  "get_asset_by_symbol": "(symbol: str) -> dict | None",
  "get_balance": "(account_id: str) -> dict",
  "get_price": "(asset_id: str, quote_id: str, as_of: str) -> dict | None",
  "get_transaction": "(id: str) -> dict",
  "goal_progress": "(account: str) -> dict",
  "holdings": "(account_id: str | None = None, asset_type: str | None = None) -> list[dict]",
  "import_file": "(file_path: str, account_id: str, counterpart_account_id: str, currency: str = 'USD', asset_id: str | None = None, date_col: str | None = None, amount_col: str | None = None, desc_col: str | None = None, inflow_col: str | None = None, outflow_col: str | None = None, counterpart_col: str | None = None, tag_cols: dict[str, str] | None = None, skip_rows: int = 0, status: str = 'pending', amount_convention: str = 'signed', show_duplicates: bool = False, statement_type: str | None = None) -> dict",
  "import_ledger": "(file_path: str | None = None, data: str | None = None, preserve_ids: bool = True, dry_run: bool = False) -> dict",
  "import_transactions": "(account_id: str, counterpart_id: str, transactions: list[dict], status: str = 'pending', dry_run: bool = False, batch_label: str | None = None, tags: dict[str, str] | None = None, amount_convention: str = 'signed', date_tolerance_days: int = 1, asset_id: str | None = None, skip_dedup: bool = False, statement_type: str | None = None) -> dict",
  "income_statement": "(year: int, month: int | None = None, branch: str | None = None, compact: bool = False, include_pending: bool = False, account_ids: list[str] | None = None, entity_id: str | None = None, quote_asset_id: str | None = None, status: str | None = None) -> dict",
  "init_defaults": "(template: str = 'personal') -> dict",
  "inspect_transaction": "(tx_id: str) -> dict",
  "integrity_check": "() -> dict",
  "invert_import": "(batch_id: str) -> dict",
  "list_accounts": "(type: str | None = None, parent_id: str | None = None, include_counts: bool = False, tree: bool = False) -> list[dict]",
  "list_assets": "(asset_type: str | None = None) -> list[dict]",
  "list_backups": "() -> list[dict]",
  "list_branches": "() -> list[dict]",
  "list_checkpoints": "() -> list[dict]",
  "list_entries": "(tx_id: str) -> list[dict]",
  "list_entries_by_asset": "(asset_id: str, limit: int = 100, offset: int = 0) -> dict",
  "list_goals": "() -> list",
  "list_import_batches": "(limit: int = 20, date_from: str | None = None) -> list[dict]",
  "list_match_rules": "() -> list[dict]",
  "list_prices": "() -> list[dict]",
  "list_scheduled": "() -> list[dict]",
  "list_tags": "(entity_type: str, entity_id: str) -> list[dict]",
  "list_transactions": "(account_id: str | None = None, category_id: str | None = None, asset_id: str | None = None, year: int | None = None, month: int | None = None, status: str | None = None, limit: int = 50, offset: int = 0, compact: bool = True, sort: str = 'date_desc') -> dict",
  "list_uncategorized": "(catch_all_account_id: str | None = None, status: str = 'pending', date_from: str | None = None, date_to: str | None = None, limit: int = 50, offset: int = 0, compact: bool = False) -> dict",
  "list_unmatched_transfers": "(date_tolerance_days: int = 3) -> list[dict]",
  "match_transfer_pairs": "(clearing_account: str | None = None, account_a: str | None = None, account_b: str | None = None, date_from: str | None = None, date_to: str | None = None, date_tolerance_days: int = 0, match_by: str = 'amount+date+code', dry_run: bool = True) -> dict",
  "match_transfers": "(account_a: str, account_b: str, date_tolerance_days: int = 1, dry_run: bool = True, status: str = 'pending') -> dict",
  "merge_accounts": "(sources: list[str], target: str, delete_sources: bool = True) -> dict",
  "merge_branch": "(source: str) -> dict",
  "migrate_asset_entries": "(from_asset_id: str, to_asset_id: str, dry_run: bool = True) -> dict",
  "move_transactions": "(from_account: str, to_account: str, dry_run: bool = True) -> dict",
  "net_worth": "(date: str | None = None, branch: str | None = None, include_pending: bool = False, quote_asset_id: str | None = None) -> dict",
  "pending_summary": "(year: int | None = None, month: int | None = None) -> dict",
  "plan_transaction": "(date: str, amount: float, from_account_id: str, to_account_id: str, description: str, branch: str | None = None) -> dict",
  "post_journal_entry": "(date: str, legs: list[dict], description: str, status: str = 'pending') -> dict",
  "preview_commit": "(as_of: str | None = None) -> dict",
  "preview_import": "(file_path: str, account_id: str, counterpart_account_id: str, rows: int = 3, currency: str = 'USD', asset_id: str | None = None, date_col: str | None = None, amount_col: str | None = None, desc_col: str | None = None, inflow_col: str | None = None, outflow_col: str | None = None, skip_rows: int = 0, amount_convention: str = 'signed', statement_type: str | None = None) -> dict",
  "process_scheduled": "(through_date: str | None = None) -> dict",
  "process_statement": "(file_path: str, account_id: str, counterpart_account_id: str, expected_balance: float | None = None, currency: str = 'USD', asset_id: str | None = None, date_col: str | None = None, amount_col: str | None = None, desc_col: str | None = None, inflow_col: str | None = None, outflow_col: str | None = None, counterpart_col: str | None = None, tag_cols: dict[str, str] | None = None, skip_rows: int = 0, amount_convention: str = 'signed', statement_type: str | None = None, transfer_account_id: str | None = None, date_tolerance_days: int = 1, commit: bool = False, show_duplicates: bool = True, preview_rows: int = 10) -> dict",
  "project_balances": "(through: str, account_ids: list[str] | None = None, include_goals: bool = False, branch: str | None = None, quote_asset_id: str | None = None) -> dict",
  "project_month_end": "(year: int | None = None, month: int | None = None, expected_inflows: list[dict] | None = None, expected_outflows: list[dict] | None = None, expected_paychecks: list[dict] | None = None, include_pending: bool = True, account_ids: list[str] | None = None, quote_asset_id: str | None = None) -> dict",
  "recategorize_by_pattern": "(pattern: str, new_account_id: str, old_account_id: str | None = None, date_from: str | None = None, date_to: str | None = None, dry_run: bool = True, persist_rule: bool = False, verbose: bool = False, status: str = 'posted', amount_min: int | None = None, amount_max: int | None = None) -> dict",
  "recategorize_by_patterns": "(rules: list[dict], date_from: str | None = None, date_to: str | None = None, dry_run: bool = True, persist_rules: bool = False, old_account_id: str | None = None, verbose: bool = False, status: str = 'posted', amount_min: int | None = None, amount_max: int | None = None) -> dict",
  "recategorize_transaction": "(tx_id: str, new_account_id: str, old_account_id: str | None = None) -> dict",
  "recognize_gain_loss": "(date: str, amount: float, investment_account_id: str, description: str, gain_loss_account_id: str | None = None, status: str = 'posted', asset_id: str | None = None) -> dict",
  "reconcile_diff": "(account_id: str, date_from: str | None = None, date_to: str | None = None, branch: str | None = None) -> dict",
  "reconcile_statement": "(account_id: str, counterpart_id: str, transactions: list[dict], amount_convention: str = 'signed', statement_type: str | None = None) -> dict",
  "reconcile_statement_plan": "(file_path: str, account_id: str, counterpart_account_id: str | None = None, expected_balance: float | None = None, currency: str = 'USD', asset_id: str | None = None, date_col: str | None = None, amount_col: str | None = None, desc_col: str | None = None, inflow_col: str | None = None, outflow_col: str | None = None, skip_rows: int = 0, amount_convention: str = 'signed', statement_type: str | None = None, date_tolerance_days: int = 3, min_likely_score: float = 0.72, sample_limit: int = 20) -> dict",
  "reconcile_to_balance": "(account_id: str, target_balance: float, offset_account_id: str, date: str, description: str | None = None, asset_id: str | None = None, status: str = 'posted', dry_run: bool = False) -> dict",
  "record_investment": "(date: str, amount: float, investment_account_id: str, source_account_id: str, description: str, status: str = 'posted', asset_id: str | None = None) -> dict",
  "record_opening_balance": "(account_id: str, amount: float, date: str, status: str = 'pending', asset_id: str | None = None, counterpart_account_id: str | None = None) -> dict",
  "record_opening_balances": "(balances: list[dict], date: str, status: str = 'pending') -> dict",
  "record_pending_expenses": "(account_id: str, transactions: list[dict], asset_id: str | None = None, batch_label: str | None = None, tags: dict[str, str] | None = None, dry_run: bool = True, skip_dedup: bool = False) -> dict",
  "reopen_period": "(checkpoint_id: str) -> dict",
  "repair_integrity": "(dry_run: bool = True, backup: bool = True) -> dict",
  "rollback_import": "(batch_id: str) -> dict",
  "rollback_recategorize": "(batch_id: str) -> dict",
  "search_transactions": "(desc: str | None = None, query: str | None = None, amount_min: int | None = None, amount_max: int | None = None, account_id: str | None = None, status: str | None = None, date_from: str | None = None, date_to: str | None = None, posted_at_from: str | None = None, posted_at_to: str | None = None, limit: int = 50, offset: int = 0, sort: str = 'date_desc') -> dict",
  "set_budget": "(account: str, amount: float, period: str = 'monthly', year: int | None = None, month: int | None = None, rollover: bool = False) -> dict",
  "set_budgets": "(budgets: list[dict], year: int | None = None, month: int | None = None) -> dict",
  "set_goal": "(account: str, target: float, name: str, target_date: str | None = None, priority: int = 1) -> dict",
  "spending": "(year: int, month: int, branch: str | None = None, include_pending: bool = False, status: str | None = None, account_ids: list[str] | None = None, entity_id: str | None = None, quote_asset_id: str | None = None) -> dict",
  "spending_rate": "(account: str | None = None, year: int | None = None, month: int | None = None, status: str = 'posted', quote_asset_id: str | None = None) -> list[dict]",
  "suggest_budgets": "(months: int = 3, year: int | None = None, month: int | None = None, skip_budgeted: bool = True) -> list[dict]",
  "top_descriptions": "(account_id: str, limit: int = 50, status: str | None = None) -> list[dict]",
  "transfer": "(from_account_id: str, to_account_id: str, amount: float, date: str, description: str, status: str = 'posted', asset_id: str | None = None) -> dict",
  "trial_balance": "(branch: str | None = None, status: str | None = None) -> dict",
  "unbudgeted_spending": "(year: int | None = None, month: int | None = None, status: str = 'posted', quote_asset_id: str | None = None) -> list[dict]",
  "update_account": "(id: str, name: str | None = None, type: str | None = None, code: str | None = None, parent_id: str | None = None, color_hex: str | None = None) -> dict",
  "update_asset": "(asset_id: str, symbol: str | None = None, name: str | None = None) -> dict",
  "void_by_filter": "(date_from: str | None = None, date_to: str | None = None, account_id: str | None = None, status: str | None = None, asset_id: str | None = None, posted_at_from: str | None = None, posted_at_to: str | None = None, dry_run: bool = True, hard_delete: bool = False) -> dict"
} as const;

export type ToolSignatureName = keyof typeof TOOL_SIGNATURES;
